// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  获取应用信息
	 * 
	 *  specta 从此函数签名自动推导 TypeScript 类型。
	 *  State 参数由 Tauri 注入，specta 自动排除，不出现在 TS 签名中。
	 *  通过窄接口调用，不直接访问 AppState 的内部字段。
	 * 
	 *  Tauri 要求包含引用参数的异步 Command 返回 Result，
	 *  此处使用 Infallible 作为错误类型，运行时不会实际产生错误。
	 */
	getAppInfo: () => typedError<AppInfo, string>(__TAURI_INVOKE("get_app_info")),
};

/* Types */
/**
 *  应用基础信息（诊断 DTO，IPC 输出）
 * 
 *  由 GetAppInfo Use Case 组合 AppMetadata + DbStatus 生成。
 *  derive Type 用于 specta 自动生成 TypeScript 类型。
 *  仅派生 Serialize（IPC 输出），不派生 Deserialize。
 */
export type AppInfo = {
	version: string,
	data_dir: string,
	db_status: DbStatus,
};

/**
 *  数据库状态
 * 
 *  `#[serde(tag = "type")]` 使 serde 生成内部标签表示：
 *  `{ "type": "NotInitialized" } | { "type": "Ready", "migration_version": 1 } | ...`
 *  specta 尊重 serde 标签策略，生成对应的 TypeScript tagged union。
 *  仅派生 Serialize（IPC 输出），不无意义地派生 Deserialize。
 */
export type DbStatus = { type: "NotInitialized" } | { type: "Ready"; migration_version: number } | { type: "Error"; message: string };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

