// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  获取应用信息
	 * 
	 *  AppHandle 由 Tauri 注入，不出现在生成的 TypeScript 参数中。
	 *  AppState 已由 Composition Root 注册为 managed state。
	 */
	getAppInfo: () => __TAURI_INVOKE<AppInfo>("get_app_info"),
};

/* Types */
/**
 *  应用基础信息（诊断 DTO，IPC 输出）
 * 
 *  由 GetAppInfo Use Case 组合 AppMetadata + DbStatus 生成。
 *  derive Type 用于 specta 自动生成 TypeScript 类型。
 *  仅派生 Serialize（IPC 输出），不派生 Deserialize。
 */
export type AppInfo = {
	version: string,
	data_dir: string,
	db_status: DbStatus,
};

/**
 *  数据库状态
 * 
 *  `#[serde(tag = "type")]` 使 serde 生成内部标签表示：
 *  `{ "type": "NotInitialized" } | { "type": "Ready", "migration_version": 1 } | ...`
 *  specta 尊重 serde 标签策略，生成对应的 TypeScript tagged union。
 *  仅派生 Serialize（IPC 输出），不无意义地派生 Deserialize。
 */
export type DbStatus = { type: "NotInitialized" } | { type: "Ready"; migration_version: number } | { type: "Error"; message: string };

